#******************************* BombCrypto Bot *********************************#
#────────────────────────────────────────────────────────────────────────────────#
#─██████████████───██████████████─██████████████───██████████████─██████████████─#
#─██░░░░░░░░░░██───██░░░░░░░░░░██─██░░░░░░░░░░██───██░░░░░░░░░░██─██░░░░░░░░░░██─#
#─██░░██████░░██───██░░██████████─██░░██████░░██───██░░██████░░██─██████░░██████─#
#─██░░██──██░░██───██░░██─────────██░░██──██░░██───██░░██──██░░██─────██░░██─────#
#─██░░██████░░████─██░░██─────────██░░██████░░████─██░░██──██░░██─────██░░██─────#
#─██░░░░░░░░░░░░██─██░░██─────────██░░░░░░░░░░░░██─██░░██──██░░██─────██░░██─────#
#─██░░████████░░██─██░░██─────────██░░████████░░██─██░░██──██░░██─────██░░██─────#
#─██░░██────██░░██─██░░██─────────██░░██────██░░██─██░░██──██░░██─────██░░██─────#
#─██░░████████░░██─██░░██████████─██░░████████░░██─██░░██████░░██─────██░░██─────#
#─██░░░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░░░██─██░░░░░░░░░░██─────██░░██─────#
#─████████████████─██████████████─████████████████─██████████████─────██████─────#
#────────────────────────────────────────────────────────────────────────────────#
#                                                                                #
#********           https://github.com/afkapp/bombcrypto-bcbot           ********#
#********       Join Us on Telegram: https://t.me/bombcryptobcbot        ********#
#                                                                                #
#********************************************************************************#
#********************* Please consider buying me a coffee :) ********************#
#********************************************************************************#
#******** BUSD/BCOIN (BEP20): 0x8c38512beca8b0b06bf4e85f67ee64a7dcdaa11a ********#
#********************************************************************************#

#****************************TELEGRAM CONFIG (OPTIONAL)**************************#
#                                                 ..
#                                            ..:::::
#                                       ..::::..::::
#                                 ...::::::. ..::::.
#                            ...:::::::..  .:::::::
#                        .:::::::::::    .::::::::.
#                         ...::::..    :::::::::::
#                                    .::::::::::::
#                                   .:::::::::::::
#                                  ::::::::::::::
#                                  ::.   .:::::-.
#                                  .        .:-:

# [en] TELEGRAM DISABLE = false | TELEGRAM ENABLE = true
# [pt_BR] TELEGRAM DESABILITADO = false | TELEGRAM HABILITADO = true 
telegram_enable: true

# [en] Get your chat_id with the @btsherald_bot: https://t.me/btsherald_bot (send /id)
# [pt_BR] Pegue o chat_id com o @btsherald_bot: https://t.me/btsherald_bot (envie /id)
#
chat_ids: ["0000000000"]

# [en] Get your token with the @botfather: https://t.me/botfather (send /newbot)
# [pt_BR] Pegue o token com o @botfather: https://t.me/botfather (envie /newbot)
botfather_token: "000000000000:0000000000000000000000000" #-> Insert your BOT FATHER TOKEN

# [en] REPORT DISABLE = false | REPORT ENABLE = true
# [pt_BR] RELATÓRIO DESABILITADO = false | RELATÓRIO HABILITADO = true
enable_coin_report: true
enable_map_report: true

format_of_image: "jpg"