#******************************* BombCrypto Bot *********************************#
#────────────────────────────────────────────────────────────────────────────────#
#─██████████████───██████████████─██████████████───██████████████─██████████████─#
#─██░░░░░░░░░░██───██░░░░░░░░░░██─██░░░░░░░░░░██───██░░░░░░░░░░██─██░░░░░░░░░░██─#
#─██░░██████░░██───██░░██████████─██░░██████░░██───██░░██████░░██─██████░░██████─#
#─██░░██──██░░██───██░░██─────────██░░██──██░░██───██░░██──██░░██─────██░░██─────#
#─██░░██████░░████─██░░██─────────██░░██████░░████─██░░██──██░░██─────██░░██─────#
#─██░░░░░░░░░░░░██─██░░██─────────██░░░░░░░░░░░░██─██░░██──██░░██─────██░░██─────#
#─██░░████████░░██─██░░██─────────██░░████████░░██─██░░██──██░░██─────██░░██─────#
#─██░░██────██░░██─██░░██─────────██░░██────██░░██─██░░██──██░░██─────██░░██─────#
#─██░░████████░░██─██░░██████████─██░░████████░░██─██░░██████░░██─────██░░██─────#
#─██░░░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░░░██─██░░░░░░░░░░██─────██░░██─────#
#─████████████████─██████████████─████████████████─██████████████─────██████─────#
#────────────────────────────────────────────────────────────────────────────────#
#                                                                                #
#********           https://github.com/afkapp/bombcrypto-bcbot           ********#
#********       Join Us on Telegram: https://t.me/bombcryptobcbot        ********#
#                                                                                #
#********************************************************************************#
#********************* Please consider buying me a coffee :) ********************#
#********************************************************************************#
#******** BUSD/BCOIN (BEP20): 0x8c38512beca8b0b06bf4e85f67ee64a7dcdaa11a ********#
#********************************************************************************#  
#                                                                                #
#   ██████╗░████████╗░██████╗  ██╗░░██╗███████╗██████╗░░█████╗░██╗░░░░░██████╗░  #
#   ██╔══██╗╚══██╔══╝██╔════╝  ██║░░██║██╔════╝██╔══██╗██╔══██╗██║░░░░░██╔══██╗  #
#   ██████╦╝░░░██║░░░╚█████╗░  ███████║█████╗░░██████╔╝███████║██║░░░░░██║░░██║  #
#   ██╔══██╗░░░██║░░░░╚═══██╗  ██╔══██║██╔══╝░░██╔══██╗██╔══██║██║░░░░░██║░░██║  #
#   ██████╦╝░░░██║░░░██████╔╝  ██║░░██║███████╗██║░░██║██║░░██║███████╗██████╔╝  #
#   ╚═════╝░░░░╚═╝░░░╚═════╝░  ╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝╚══════╝╚═════╝░  #
#                                                                                #
#   [en] Enable to receive notification or a call if BCBOT stops.                #
#    ---->   Get your key: https://herald.btscenter.net                          #
#                                                                                #
#   [pt_BR] Habilitar para receber notificação ou uma ligação se o BCBOT parar.  #
#    ---->   Obtenha a chave: https://herald.btscenter.net                       #

  herald_active: false  
  key-herald: '00000000000000'
  label: 'BCBOT-1'
    
#********************************************************************************#
